### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by wincent**
Given recent Slack threads about dependencies updates, I'm doing a minimal update here (ie. `yarn upgrade-interactive`) to get us part way towards being totally up-to-date. Based on the output of `yarn outdated`, proceeding further is going to be costly:

```
yarn outdated v1.17.3
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
Package                       Current Wanted Latest Workspace               Package Type           URL
ansi-colors                   3.2.4   3.2.4  4.1.1                          resolutionDependencies https://github.com/doowb/ansi-colors
async                         2.6.3   2.6.3  3.1.0  liferay-theme-tasks     dependencies           https://caolan.github.io/async/
async                         1.5.2   1.5.2  3.1.0  generator-liferay-theme dependencies           https://caolan.github.io/async/
chai                          1.10.0  1.10.0 4.2.0  generator-liferay-theme devDependencies        http://chaijs.com
chai-fs                       0.1.0   0.1.0  2.0.0  generator-liferay-theme devDependencies        https://github.com/chaijs/chai-fs#readme
cross-spawn                   2.2.3   2.2.3  7.0.0  liferay-theme-tasks     dependencies           https://github.com/moxystudio/node-cross-spawn
del                           4.1.1   4.1.1  5.1.0  liferay-theme-tasks     dependencies           https://github.com/sindresorhus/del#readme
diff                          1.4.0   1.4.0  4.0.1  liferay-theme-tasks     dependencies           https://github.com/kpdecker/jsdiff#readme
eslint                        5.16.0  5.16.0 6.4.0                          devDependencies        https://eslint.org
eslint-config-liferay         3.0.0   3.0.0  9.0.0                          devDependencies        https://github.com/liferay/eslint-config-liferay.git
fs-extra                      0.24.0  0.24.0 8.1.0  liferay-theme-tasks     dependencies           https://github.com/jprichardson/node-fs-extra
globby                        4.1.0   4.1.0  10.0.1 liferay-theme-tasks     dependencies           https://github.com/sindresorhus/globby#readme
gulp                          3.9.1   3.9.1  4.0.2  liferay-theme-tasks     devDependencies        https://gulpjs.com
gulp                          3.9.1   3.9.1  4.0.2  generator-liferay-theme devDependencies        https://gulpjs.com
gulp                          3.9.1   3.9.1  4.0.2                          dependencies           https://gulpjs.com
gulp-debug                    2.1.2   2.1.2  4.0.0  liferay-theme-tasks     dependencies           https://github.com/sindresorhus/gulp-debug#readme
gulp-filter                   2.0.2   2.0.2  6.0.0  liferay-theme-tasks     dependencies           https://github.com/sindresorhus/gulp-filter#readme
gulp-if                       2.0.2   2.0.2  3.0.0  liferay-theme-tasks     dependencies           https://github.com/robrich/gulp-if
gulp-istanbul                 0.10.4  0.10.4 1.1.3  generator-liferay-theme devDependencies        https://github.com/SBoudrias/gulp-istanbul
gulp-load-plugins             1.6.0   1.6.0  2.0.1  liferay-theme-tasks     dependencies           https://github.com/jackfranklin/gulp-load-plugins.git
gulp-mocha                    2.2.0   2.2.0  7.0.1  generator-liferay-theme devDependencies        https://github.com/sindresorhus/gulp-mocha#readme
gulp-sass                     3.2.1   3.2.1  4.0.2  liferay-theme-tasks     dependencies           https://github.com/dlmanning/gulp-sass#readme
gulp-sourcemaps               1.6.0   1.6.0  2.6.5  liferay-theme-tasks     dependencies           http://github.com/gulp-sourcemaps/gulp-sourcemaps
gulp-zip                      3.2.0   3.2.0  5.0.0  liferay-theme-tasks     dependencies           https://github.com/sindresorhus/gulp-zip#readme
inquirer                      0.12.0  0.12.0 7.0.0  generator-liferay-theme dependencies           https://github.com/SBoudrias/Inquirer.js#readme
inquirer                      0.12.0  0.12.0 7.0.0  liferay-theme-tasks     dependencies           https://github.com/SBoudrias/Inquirer.js#readme
liferay-frontend-theme-styled 3.0.18  3.0.18 4.0.15 liferay-theme-tasks     devDependencies        https://github.com/liferay/liferay-portal.git
node-bourbon                  4.2.3   4.2.3  4.2.8  liferay-theme-tasks     dependencies           https://github.com/lacroixdesign/node-bourbon#readme
npm-keyword                   5.0.0   5.0.0  6.1.0  liferay-theme-tasks     dependencies           https://github.com/sindresorhus/npm-keyword#readme
opn                           5.5.0   5.5.0  6.0.0  liferay-theme-tasks     dependencies           https://github.com/sindresorhus/open#readme
package-json                  5.0.0   5.0.0  6.5.0  liferay-theme-tasks     dependencies           https://github.com/sindresorhus/package-json#readme
replace-in-file               3.4.4   3.4.4  4.1.3                          dependencies           https://github.com/adamreisnz/replace-in-file#readme
sinon                         1.17.7  1.17.7 7.4.2  generator-liferay-theme devDependencies        https://sinonjs.org/
sinon                         4.5.0   4.5.0  7.4.2                          devDependencies        https://sinonjs.org/
strip-ansi                    3.0.1   3.0.1  5.2.0  generator-liferay-theme devDependencies        https://github.com/chalk/strip-ansi#readme
tar-fs                        1.16.3  1.16.3 2.0.0  liferay-theme-tasks     dependencies           https://github.com/mafintosh/tar-fs
through2                      2.0.5   2.0.5  3.0.1  liferay-theme-tasks     dependencies           https://github.com/rvagg/through2#readme
vinyl-paths                   1.0.0   1.0.0  3.0.0  liferay-theme-tasks     dependencies           https://github.com/sindresorhus/vinyl-paths#readme
yeoman-generator              3.2.0   3.2.0  4.0.2  generator-liferay-theme dependencies           http://yeoman.io
yosay                         0.3.0   0.3.0  2.0.2  generator-liferay-theme dependencies           http://yeoman.io
```

### CODE REVIEW

**Comment by wincent** [comment]
Going to merge this seeing as it is a routine update.

**Comment by TBurk83** [comment]
Hase there been any movement on this? Does someone else need to pick it up?

**Comment by wincent** [comment]
@TBurk83: IIRC, the PR got merged but we didn't cut a release immediately because we wanted to to see if there was any other inbound stuff. Seeing as nothing else has come along, and I am not aware of anything else in the immediate pipeline, we may as well just publish.

**Comment by wincent** [comment]
I just published v8.1.2 and v9.4.1 releases. These just include the conservative dependency updates (no major version changes); at another time we can look at doing a more aggressive update.

**Pull request merged**
